### ISSUE TITLE
License

### ISSUE THREAD

**Issue by titanism** [matthewmueller/combine-errors#4]
This project is missing a license in `package.json` and in the Git repo.  Curious if this is MIT?

**Comment by titanism** [comment]
Closing as we see it says "MIT" in the README.  Note that it's missing in `package.json`

**Comment by ctmay4** [comment]
Any chance you could add the license? The problem I am running into was trying to get a webjar deployed for a library (https://webjars.org) that uses this as a depenency. Maven Central doesn't allow libraries to be deployed without a license and the process can't determine the license. The README is not enough for it.

```
Resolving licenses & dependencies for org.webjars.npm github-com-matthewmueller-combine-errors 3.0.3
The license could not be determined for NPM - https://github.com/matthewmueller/combine-errors 3.0.3
a.a.CoordinatedShutdown - Running CoordinatedShutdown with reason [ApplicationStoppedReason]
```
